version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres_portais
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_portais
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
